from __future__ import annotations

RECOMMENDATION_STRATEGY = "rule_based_mock_v0"
RECOMMENDATION_RULE_VERSION = "ruleset-2026-07-27-gate-4o"
RECOMMENDATION_INTENT_PARSER_VERSION = "intent-parser-v0"
RECOMMENDATION_RANKER_VERSION = "ranker-v0"
RECOMMENDATION_FIXTURE_SET_VERSION = "fixtures-v0"

RECOMMENDATION_VERSION_METADATA = {
    "strategy": RECOMMENDATION_STRATEGY,
    "rule_version": RECOMMENDATION_RULE_VERSION,
    "intent_parser_version": RECOMMENDATION_INTENT_PARSER_VERSION,
    "ranker_version": RECOMMENDATION_RANKER_VERSION,
    "fixture_set_version": RECOMMENDATION_FIXTURE_SET_VERSION,
}
